services:
  - type: web
    name: btn-services
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: btn-services-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: REPL_ID
        sync: false
      - key: REPLIT_DOMAINS
        sync: false
      - key: ISSUER_URL
        value: https://replit.com/oidc

databases:
  - name: btn-services-db
    databaseName: btn_services
    user: btn_services_user